export const customCalculatorDropdownStyles = {
  control: (provided) => ({
    ...provided,
    padding: "0 2px",
    boxShadow: "none",
    paddingTop: "0",
    marginTop: "0",
    height: "20px",
    minHeight: "20px",
    fontSize: "10px",
    textAlign: "center",
    width: "100%",
  }),
  indicatorSeparator: (provided) => ({
    ...provided,
    display: "none",
  }),
  indicatorsContainer: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0",
    fontWeight: "normal",
    fontSize: "8px",
    height: "20px",
    minHeight: "10px",
  }),
  dropdownIndicator: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0",
    paddingTop: "0",
    height: "10px", 
    width: "10px", 
    fontSize: "10px", 
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  }),
  singleValue: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0px",
    paddingTop: "0px",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "10px",
    fontSize: "10px",
  }),
  placeholder: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0",
    paddingTop: "0",
    textAlign: "center",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "20px", // Matches control height for proper alignment
    fontSize: "10px",
  }),
  valueContainer: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0",
    paddingTop: "0",
    height: "20px",
    fontSize: "10px", 
    minHeight: "0px",
    display: "flex",
    alignItems: "center", // Ensure vertical centering
  }),
  input: (provided) => ({
    ...provided,
    padding: "0",
    margin: "0",
    marginTop: "0",
    paddingTop: "0",

    height: "20px", // Matches control height for proper alignment
    fontSize: "10px",
  }),
  option: (provided) => ({
    ...provided,
    padding: "0px",
    margin: "0px",
  }),
  menu: (provided) => ({
    ...provided,
    padding: "2px",
    zIndex: 1000,
  }),
  menuList: (provided) => ({
    ...provided,
    padding: "2px",
    margin: "0px",
  }),
};
