export const stateData = [
    { id: "AB", label: "Alberta", query: "state" },
    { id: "BC", label: "British Columbia", query: "state" },
    { id: "MB", label: "Manitoba", query: "state" },
    { id: "NB", label: "New Brunswick", query: "state" },
    { id: "NL", label: "Newfoundland and Labrador", query: "state" },
    { id: "NT", label: "Northwest Territories", query: "state" },
    { id: "NS", label: "Nova Scotia", query: "state" },
    { id: "NU", label: "Nunavut", query: "state" },
    { id: "ON", label: "Ontario", query: "state" },
    { id: "PE", label: "Prince Edward Island", query: "state" },
    { id: "QC", label: "Quebec", query: "state" },
    { id: "SK", label: "Saskatchewan", query: "state" },
    { id: "YT", label: "Yukon", query: "state" },
    { id: "AL", label: "Alabama", query: "state" },
    { id: "AK", label: "Alaska", query: "state" },
    { id: "AZ", label: "Arizona", query: "state" },
    { id: "AR", label: "Arkansas", query: "state" },
    { id: "CA", label: "California", query: "state" },
    { id: "CO", label: "Colorado", query: "state" },
    { id: "CT", label: "Connecticut", query: "state" },
    { id: "DE", label: "Delaware", query: "state" },
    { id: "DC", label: "District of Columbia", query: "state" },
    { id: "FL", label: "Florida", query: "state" },
    { id: "GA", label: "Georgia", query: "state" },
    { id: "HI", label: "Hawaii", query: "state" },
    { id: "ID", label: "Idaho", query: "state" },
    { id: "IL", label: "Illinois", query: "state" },
    { id: "IN", label: "Indiana", query: "state" },
    { id: "IA", label: "Iowa", query: "state" },
    { id: "KS", label: "Kansas", query: "state" },
    { id: "KY", label: "Kentucky", query: "state" },
    { id: "LA", label: "Louisiana", query: "state" },
    { id: "ME", label: "Maine", query: "state" },
    { id: "MD", label: "Maryland", query: "state" },
    { id: "MA", label: "Massachusetts", query: "state" },
    { id: "MI", label: "Michigan", query: "state" },
    { id: "MN", label: "Minnesota", query: "state" },
    { id: "MS", label: "Mississippi", query: "state" },
    { id: "MO", label: "Missouri", query: "state" },
    { id: "MT", label: "Montana", query: "state" },
    { id: "NE", label: "Nebraska", query: "state" },
    { id: "NV", label: "Nevada", query: "state" },
    { id: "NH", label: "New Hampshire", query: "state" },
    { id: "NJ", label: "New Jersey", query: "state" },
    { id: "NM", label: "New Mexico", query: "state" },
    { id: "NY", label: "New York", query: "state" },
    { id: "NC", label: "North Carolina", query: "state" },
    { id: "ND", label: "North Dakota", query: "state" },
    { id: "OH", label: "Ohio", query: "state" },
    { id: "OK", label: "Oklahoma", query: "state" },
    { id: "OR", label: "Oregon", query: "state" },
    { id: "PA", label: "Pennsylvania", query: "state" },
    { id: "RI", label: "Rhode Island", query: "state" },
    { id: "SC", label: "South Carolina", query: "state" },
    { id: "SD", label: "South Dakota", query: "state" },
    { id: "TN", label: "Tennessee", query: "state" },
    { id: "TX", label: "Texas", query: "state" },
    { id: "UT", label: "Utah", query: "state" },
    { id: "VT", label: "Vermont", query: "state" },
    { id: "VA", label: "Virginia", query: "state" },
    { id: "WA", label: "Washington", query: "state" },
    { id: "WV", label: "West Virginia", query: "state" },
    { id: "WI", label: "Wisconsin", query: "state"   },
    { id: "WY", label: "Wyoming", query: "state" },
    { id: "AS", label: "American Samoa", query: "state" },
    { id: "GU", label: "Guam", query: "state" },
    { id: "MP", label: "Northern Mariana Islands", query: "state" },
    { id: "PR", label: "Puerto Rico" },
    { id: "VI", label: "U.S. Virgin Islands" },
  ];