export const atvData = [
    { label: "Florida", value: "Florida", rate: 500 },
    { label: "Georgia", value: "Georgia", rate: 660 },
    { label: "South Carolina", value: "South Carolina", rate: 500 },
    { label: "Alabama", value: "Alabama", rate: 640 },
    { label: "North Carolina", value: "North Carolina", rate: 700 },
    { label: "Tennessee", value: "Tennessee", rate: 950 },
    { label: "Kentucky", value: "Kentucky", rate: 950 },
    { label: "Mississippi", value: "Mississippi", rate: 850 },
    { label: "Louisiana", value: "Louisiana", rate: 900 },
    { label: "Delaware", value: "Delaware", rate: 1081.50 },
    { label: "Maryland", value: "Maryland", rate: 990 },
    { label: "West Virginia", value: "West Virginia", rate: 1056 },
    { label: "Indiana", value: "Indiana", rate: 1023 },
    { label: "Ohio", value: "Ohio", rate: 990 },
    { label: "Pennsylvania", value: "Pennsylvania", rate: 957 },
    { label: "New Jersey", value: "New Jersey", rate: 882 },
    { label: "Arkansas", value: "Arkansas", rate: 924 },
    { label: "Missouri", value: "Missouri", rate: 996 },
    { label: "Illinois", value: "Illinois", rate: 960 },
    { label: "Texas", value: "Texas", rate: 924 },
    { label: "Oklahoma", value: "Oklahoma", rate: 1050 },
    { label: "Nebraska", value: "Nebraska", rate: 1200 },
    { label: "Wisconsin", value: "Wisconsin", rate: 1155 },
    { label: "Minnesota", value: "Minnesota", rate: 1200 },
    { label: "Colorado", value: "Colorado", rate: 1184 },
    { label: "South Dakota", value: "South Dakota", rate: 1314 },
    { label: "North Dakota", value: "North Dakota", rate: 1278 },
    { label: "New Mexico", value: "New Mexico", rate: 1596 },
    { label: "Arizona", value: "Arizona", rate: 1260 },
    { label: "Montana", value: "Montana", rate: 1610 },
    { label: "Wyoming", value: "Wyoming", rate: 1562 },
    { label: "Utah", value: "Utah", rate: 1679 },
    { label: "Idaho", value: "Idaho", rate: 1679 },
    { label: "Oregon", value: "Oregon", rate: 1898 },
    { label: "California", value: "California", rate: 1890 },
    { label: "Washington", value: "Washington", rate: 1836 },
    { label: "Nevada", value: "Nevada", rate: 2464 },
  ];

  export const suvData = [
    { label: "Florida", value: "Florida", rate: 600 },
    { label: "Georgia", value: "Georgia", rate: 660 },
    { label: "South Carolina", value: "South Carolina", rate: 700 },
    { label: "Alabama", value: "Alabama", rate: 640 },
    { label: "North Carolina", value: "North Carolina", rate: 700 },
    { label: "Tennessee", value: "Tennessee", rate: 950 },
    { label: "Kentucky", value: "Kentucky", rate: 950 },
    { label: "Mississippi", value: "Mississippi", rate: 850 },
    { label: "Louisiana", value: "Louisiana", rate: 900 },
    { label: "Delaware", value: "Delaware", rate: 1417.50 },
    { label: "Maryland", value: "Maryland", rate: 1290 },
    { label: "West Virginia", value: "West Virginia", rate: 1353 },
    { label: "Indiana", value: "Indiana", rate: 1287 },
    { label: "Ohio", value: "Ohio", rate: 1221 },
    { label: "Pennsylvania", value: "Pennsylvania", rate: 1155 },
    { label: "New Jersey", value: "New Jersey", rate: 1039.50 },
    { label: "Arkansas", value: "Arkansas", rate: 1056 },
    { label: "Missouri", value: "Missouri", rate: 1104 },
    { label: "Illinois", value: "Illinois", rate: 1056 },
    { label: "Texas", value: "Texas", rate: 1008 },
    { label: "Oklahoma", value: "Oklahoma", rate: 1120 },
    { label: "Nebraska", value: "Nebraska", rate: 1275 },
    { label: "Wisconsin", value: "Wisconsin", rate: 1260 },
    { label: "Minnesota", value: "Minnesota", rate: 1328 },
    { label: "Colorado", value: "Colorado", rate: 1312 },
    { label: "South Dakota", value: "South Dakota", rate: 1440 },
    { label: "North Dakota", value: "North Dakota", rate: 1422 },
    { label: "New Mexico", value: "New Mexico", rate: 1463 },
    { label: "Arizona", value: "Arizona", rate: 1520 },
    { label: "Montana", value: "Montana", rate: 1748 },
    { label: "Wyoming", value: "Wyoming", rate: 1672 },
    { label: "Utah", value: "Utah", rate: 1748 },
    { label: "Idaho", value: "Idaho", rate: 1748 },
    { label: "Oregon", value: "Oregon", rate: 1976 },
    { label: "California", value: "California", rate: 2052 },
    { label: "Washington", value: "Washington", rate: 2052 },
    { label: "Nevada", value: "Nevada", rate: 2352 },
    // { label: "ONTARIO", value: "ONTARIO", rate: 99999 },
  ];

  export const heavyMachineryData = [
    { label: "Florida", value: "Florida", rate: 1280 },
    { label: "Georgia", value: "Georgia", rate: 2640 },
    { label: "South Carolina", value: "South Carolina", rate: 2000 },
    { label: "Alabama", value: "Alabama", rate: 2560 },
    { label: "North Carolina", value: "North Carolina", rate: 2800 },
    { label: "Tennessee", value: "Tennessee", rate: 3800 },
    { label: "Kentucky", value: "Kentucky", rate: 3800 },
    { label: "Mississippi", value: "Mississippi", rate: 3400 },
    { label: "Louisiana", value: "Louisiana", rate: 3600 },
    { label: "Delaware", value: "Delaware", rate: 4200 },
    { label: "Maryland", value: "Maryland", rate: 4000 },
    { label: "West Virginia", value: "West Virginia", rate: 4400 },
    { label: "Indiana", value: "Indiana", rate: 4400 },
    { label: "Ohio", value: "Ohio", rate: 4400 },
    { label: "Pennsylvania", value: "Pennsylvania", rate: 4400 },
    { label: "New Jersey", value: "New Jersey", rate: 4200 },
    { label: "Arkansas", value: "Arkansas", rate: 4400 },
    { label: "Missouri", value: "Missouri", rate: 4800 },
    { label: "Illinois", value: "Illinois", rate: 4800 },
    { label: "Texas", value: "Texas", rate: 4800 },
    { label: "Kansas", value: "Kansas", rate: 5600 },
    { label: "Iowa", value: "Iowa", rate: 5600 },
    { label: "New Hampshire", value: "New Hampshire", rate: 5600 },
    { label: "Vermont", value: "Vermont", rate: 5600 },
    { label: "Oklahoma", value: "Oklahoma", rate: 5600 },
    { label: "Nebraska", value: "Nebraska", rate: 6000 },
    { label: "Wisconsin", value: "Wisconsin", rate: 6000 },
    { label: "Minnesota", value: "Minnesota", rate: 6400 },
    { label: "Colorado", value: "Colorado", rate: 6400 },
    { label: "South Dakota", value: "South Dakota", rate: 7200 },
    { label: "North Dakota", value: "North Dakota", rate: 7200 },
    { label: "New Mexico", value: "New Mexico", rate: 7600 },
    { label: "Arizona", value: "Arizona", rate: 8000 },
    { label: "Montana", value: "Montana", rate: 9200 },
    { label: "Wyoming", value: "Wyoming", rate: 8800 },
    { label: "Utah", value: "Utah", rate: 9200 },
    { label: "Idaho", value: "Idaho", rate: 9200 },
    { label: "Oregon", value: "Oregon", rate: 10400 },
    { label: "California", value: "California", rate: 10800 },
    { label: "Washington", value: "Washington", rate: 10800 },
    { label: "Nevada", value: "Nevada", rate: 11200 },
    { label: "Alaska", value: "Nevada", rate: 15200 },
    { label: "Hawaii", value: "Nevada", rate: 19600 },
  ];