export const transactions = [
    {
      id: "39635",
      recipient: "Kristin Watson",
      date: "17 Oct, 2020",
      location: "Orange",
      amount: "$119.99",
      status: "Completed",
    },
    {
      id: "22739",
      recipient: "Theresa Webb",
      date: "1 Feb, 2020",
      location: "Fairfield",
      amount: "$129.99",
      status: "Canceled",
    },
    {
      id: "43178",
      recipient: "Darlene Robertson",
      date: "21 Sep, 2020",
      location: "Toledo",
      amount: "$49.99",
      status: "Pending",
    },
    {
      id: "43178",
      recipient: "Annette Black",
      date: "8 Sep, 2020",
      location: "Toledo",
      amount: "$109.99",
      status: "Completed",
    },
    {
      id: "97174",
      recipient: "Savannah Nguyen",
      date: "1 Feb, 2020",
      location: "Toledo",
      amount: "$69.99",
      status: "Canceled",
    },
    {
      id: "43756",
      recipient: "Floyd Miles",
      date: "17 Oct, 2020",
      location: "Naperville",
      amount: "$59.99",
      status: "Completed",
    },
    {
      id: "43756",
      recipient: "Darrell Steward",
      date: "24 May, 2020",
      location: "Toledo",
      amount: "$129.99",
      status: "Pending",
    },
    {
      id: "70668",
      recipient: "Marvin McKinney",
      date: "22 Oct, 2020",
      location: "Austin",
      amount: "$69.99",
      status: "Completed",
    },
    {
      id: "70668",
      recipient: "Esther Howard",
      date: "1 Feb, 2020",
      location: "Pembroke Pines",
      amount: "$99.99",
      status: "Canceled",
    },
    {
      id: "39635",
      recipient: "Jenny Wilson",
      date: "22 Oct, 2020",
      location: "Fairfield",
      amount: "$79.99",
      status: "Pending",
    },
    {
      id: "43178",
      recipient: "Cody Fisher",
      date: "21 Sep, 2020",
      location: "Fairfield",
      amount: "$89.99",
      status: "Pending",
    },
  ]